# This is a basic workflow to help you get started with Actions

name: tiwen

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:

  workflow_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '0 22 * * *'
    watch:
        types: 
            - started
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        sudo apt-get install python3-bs4
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        python3 tiwen.py <<EOF
        
        EOF
